### ISSUE TITLE
pre-commit hook in GitHub Action

### ISSUE THREAD

**Issue by morremeyer** [norwoodj/helm-docs#100]
Hey and thanks for this tool, it makes my life easier :) 

I was wondering how I can use the pre-commit hook with a GitHub action? If I use the official GitHub action for pre-commit and install `helm-docs` like this, it fails with `Please install helm-docs to run the pre-commit hook! https://github.com/norwoodj/helm-docs#installation`:

```
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.16.4'
    - name: Install helm-docs
      run: GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
    - run: helm docs
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
```

Is this due to the pre-commit action being run in its own container, can you maybe help me out here?

**Comment by macobo** [comment]
Here's how my github action looks like:

```
name: Update docs

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run helm-docs
        run: |
          GOBIN=$PWD GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
          ./helm-docs --sort-values-order file
          rm helm-docs

      - name: Commit bump
        uses: EndBug/add-and-commit@v7
        with:
            branch: ${{ github.event.pull_request.base.ref }}
            message: 'Regenerate chart README.md'
```
