### ISSUE TITLE
Proposal: pretty pring json values

### ISSUE THREAD

**Issue by mac2000** [norwoodj/helm-docs#116]
Sample yml:

```yml
loki:
  enabled: true
  tolerations:
  # -- because we are deploying to a system node need this toleration
  - key: "dedicated.deckhouse.io"
    operator: "Equal"
    value: "system"
    effect: "NoSchedule"
  persistence:
    storageClassName: local-storage
    enabled: true
    # -- size will be used for persisten volume and passed to loki configs
    size: 10Gi
    # -- node on which data will be stored, make sure to create `/mnt/kubernetes/loki`
    node: kube-stage-system-0
```

Gives an output:

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| loki.enabled | bool | `true` |  |
| loki.persistence.enabled | bool | `true` |  |
| loki.persistence.node | string | `"kube-stage-system-0"` | node on which data will be stored, make sure to create `/mnt/kubernetes/loki` |
| loki.persistence.size | string | `"10Gi"` | size will be used for persisten volume and passed to loki configs |
| loki.persistence.storageClassName | string | `"local-storage"` |  |
| loki.tolerations[0] | object | `{"effect":"NoSchedule","key":"dedicated.deckhouse.io","operator":"Equal","value":"system"}` | because we are deploying to a system node need this toleration |

Which forces scroll and description column becomes really small

Will be nice if output will be:

<table>
<tr>
<th>Key</th>
<th>Type</th>
<th>Default</th>
<th>Description</th>
</tr>
<tr>
<td>loki.enabled</td>
<td>bool</td>
<td><code>true</code></td>
<td></td>
</tr>
<tr>
<td>loki.persistence.enabled</td>
<td>bool</td>
<td><code>true</code></td>
<td></td>
</tr>
<tr>
<td>loki.persistence.node</td>
<td>string</td>
<td><code>"kube-stage-system-0"</code></td>
<td>node on which data will be stored, make sure to create `/mnt/kubernetes/loki`</td>
</tr>
<tr>
<td>loki.persistence.size</td>
<td>string</td>
<td><code>"10Gi"</code></td>
<td>size will be used for persisten volume and passed to loki configs</td>
</tr>
<tr>
<td>loki.persistence.storageClassName</td>
<td>string</td>
<td><code>"local-storage"</code></td>
<td></td>
</tr>
<tr>
<td>loki.tolerations[0]</td>
<td>object</td>
<td><pre>{
  "effect": "NoSchedule",
  "key": "dedicated.deckhouse.io",
  "operator": "Equal",
  "value": "system"
}</pre></td>
<td>because we are deploying to a system node need this toleration</td>
</tr>
</table>

> Unfortunately it seems that GitHub markdown does not allow multiline values in tables so there is no other way than render HTML table.
