### ISSUE TITLE
[question] how to ignore templates in .gotmpl

### ISSUE THREAD

**Issue by CrystalMethod** [norwoodj/helm-docs#125]
Is it possible to ignore (disable) certain templates to be evaluated?

While the first template taken from "example-charts/custom-template/README.md.gotmpl" is expected to be evaluated.

##### README.md.gotmpl
```
```console
$ helm repo add foo-bar http://charts.foo-bar.com
$ helm install my-release foo-bar/{{ template "chart.name" . }}
```

##### README.md
```
```console
$ helm repo add foo-bar http://charts.foo-bar.com
$ helm install my-release foo-bar/custom-template
```
... the template taken from our "README.md.gotmpl" is expected to not be evaluated since it is a snippet to show how users can use that config value. The generated markdown stops at this point.

##### README.md.gotmpl
```
```yaml
extraEnvVars:
  - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
    value: '{{ template "common.names.fullname" . }}'
```

##### README.md
```
```yaml
extraEnvVars:
  - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
    value: '
```
