### ISSUE TITLE
Inconsistent description

### ISSUE THREAD

**Issue by HaripriyaRegula** [norwoodj/helm-docs#127]
Hi Team,

I see the expected description is missing for the comments quoted.
For the below input YAML content, the result is attached and highlighted.

![helm-docs-missing-description](https://user-images.githubusercontent.com/100826620/156523246-363f2e09-a770-4c9b-8a6c-162846c85a6a.png)

```
# --   Number of desired pods.
replicaCount: 1
nfConfig:
  nfService:
# --   Name of the service to monitor.
    name: config-service-name
# --   DEPRECATED. Will be removed
  nrfServer: []
nfProfile:
# --   DEPRECATED. Will be removed
  sNssais:
  nfSetIdList:
  nfServices:
# --   DEPRECATED. Will be removed
  - serviceName: nfServiceOne
# --   DEPRECATED. Will be removed
    versions:
    - apiFullVersion: 1.0.1
      apiVersionInUri: v1
# --   DEPRECATED. Will be removed
    allowedNfTypes:
    - RRR
# --   DEPRECATED. Will be removed
    sNssais:
# --   DEPRECATED. Will be removed
  - serviceName: nfServiceTwo
# --   DEPRECATED. Will be removed
    versions:
    - apiFullVersion: 2.0.0
      apiVersionInUri: v2
# --   DEPRECATED. Will be removed
    allowedNfTypes:
    - SSS
    - SSSS
# --   DEPRECATED. Will be removed
    allowedOperationsPerInstance:
# --   DEPRECATED. Will be removed
  heartBeatTimer: 120
# --   DEPRECATED. Will be removed
  allowedPlmns:
Reporting:
# --   DEPRECATED. Will be removed
  enabled: true
publishing:
  hello: true

```

Please analyze and suggest us a way forward.

Thanks
Haripriya
