### ISSUE TITLE
Pre-commit hooks ignores -s argument

### ISSUE THREAD

**Issue by emanuele-leopardi** [norwoodj/helm-docs#160]
```
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
        args:
          - -s file
 ```
Given the above I was expecting helm-docs to keep the order in the table as the file itself, instead it still processes it as this argument hasn't been passed and sets all up alphanumerically

Another test I tried was the following
```
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
        args:
          - -s filefafsfd
 ```
this again gets completely ignored

**Comment by sc250024** [comment]
I think this is related to how `pre-commit` / YAML in general handles command line arguments. Have you tried the following?

```yaml
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
        args:
          - -s
          - filefafsfd
```

Putting the argument on a separate line might do the trick. Alternatively, you can use the long-arg format with an `=` sign like so:

```yaml
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
        args:
          - --sort-values-order=filefafsfd
```
