### ISSUE TITLE
document-dependency-values does not work with OCI dependency

### ISSUE THREAD

**Issue by hlavki** [norwoodj/helm-docs#163]
Hi, I tried to run `helm-docs --document-dependency-values` for umbrella chart:

```yaml
name: user
version: 0.0.1
description: User API

dependencies:
  - name: spring-boot
    version: 0.0.3
    repository: oci://harbor.company.com/charts
```
But result does not contain values from `spring-boot` dependency chart.
