### ISSUE TITLE
Pipe `|` breaks table output of `values.yml`

### ISSUE THREAD

**Issue by BWibo** [norwoodj/helm-docs#171]
Hey there,

this is similar to #118. 

I have following in a `values.yml`:

```yaml
readinessProbe:
  # -- Enable/disable readiness probe
  # [Readiness probe](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes)
  # See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Probe) for details.
  # Use `readinessProbe.probe: {}` to configure
  # [readinessProbe probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
  terminationGracePeriodSeconds:
  probe:
    exec:
      command: [ bash, -c, 'wget -S "http://127.0.0.1:3000/api/health" |& grep "200 OK"' ] 
 ```
Apparently, the pipe in the command is interpreted as a column separator in the generated markdown:

```md
| readinessProbe.probe.exec.command[2] | string | `"wget -S \"http://127.0.0.1:3000/api/health\" |& grep \"200 OK\""` |  |
```
Rendered result:
![grafik](https://user-images.githubusercontent.com/7643434/216573000-2d2d1d51-05cd-485e-9407-9353f9aa8e0a.png)

Escaping the pipe manually seems to help:

```md
| readinessProbe.probe.exec.command[2] | string | `"wget -S \"http://127.0.0.1:3000/api/health\" \|& grep \"200 OK\""` |  |
```
 
![grafik](https://user-images.githubusercontent.com/7643434/216573815-57bd3c5d-d261-432d-a460-97a5e731435b.png)

Version info:

```console
$ docker run --rm --volume "$PWD/helm/charts:/helm-docs" -u $(id -u) jnorwood/helm-docs:latest --version
helm-docs version 1.11.0
```
