### ISSUE TITLE
Notation annotation ignored when value is null

### ISSUE THREAD

**Issue by sblundy** [norwoodj/helm-docs#183]
If a field is annotated with a `notationType`, but the value is `null`, the annotation is ignored. In the example below, it would be as if `@notationType -- yaml` weren't there.

```yaml
animals:
  # -- (list) Declaring object as yaml with null value
  # @notationType -- yaml
  lizards: 
```

Apply this patch to reproduce the problem: [notation-test.patch](https://github.com/norwoodj/helm-docs/files/12030861/notation-test.patch)
