### ISSUE TITLE
How to document a list of objects?

### ISSUE THREAD

**Issue by idogada-akamai** [norwoodj/helm-docs#185]
Hello,

I have a values file that looks similar to this:

```
kafka:
  # -- Keda scaledObjects to create and configure
  # Look at the [values.yaml](values.yaml) file for examples
  # @default `[]`
  scaledObjects:

    - # -- The name of the scaled object
      name: kafka-ABC
      # -- The target resource name to scale
      scaleTargetRef: da-ABC
      consumerGroupSuffix: _abc
      topicSuffix: _abc

    - name: kafka-def
      scaleTargetRef: da-def
      consumerGroupSuffix: _def
      topicSuffix: _def
```

If I generate a doc base on that I get the following table:
| Key | Type | Default | Description |
|-----|------|---------|-------------|
| kafka.scaledObjects | list | `[]` | Keda scaledObjects to create and configure Look at the [values.yaml](values.yaml) file for examples |
| kafka.scaledObjects[0].name | string | `"kafka-ABC"` | The name of the scaled object |
| kafka.scaledObjects[0].scaleTargetRef | string | `"da-ABC"` | The target resource name to scale |

I want to to set kafka.scaledObjects to an empty list (`[]`). And then have the table looking looking something like this
| Key | Type | Default | Description |
|-----|------|---------|-------------|
| kafka.scaledObjects | list | `[]` | Keda scaledObjects to create and configure Look at the [values.yaml](values.yaml) file for examples |
| kafka.scaledObjects[].name | string | | The name of the scaled object |
| kafka.scaledObjects[].scaleTargetRef | string | | The target resource name to scale |
| kafka.scaledObjects[].topicSuffix | string | | The Kafka topic suffix. Will be prefixed by `.Values.instance_name` |
| kafka.scaledObjects[].consumerGroupSuffix | string | | The Kafka consumer group suffix. Will be prefixed by `.Values.instance_name` |

Do you know how can I achieve this?
