### ISSUE TITLE
[Bug]: Segmentation violation when using templates in `values.yml`

### ISSUE THREAD

**Issue by BWibo** [norwoodj/helm-docs#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the [bitnami/common](https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_tplvalues.tpl) template renderer, which allows to put templates in `values.yml` this causes a segfault.

### statefulset.yml

```yml
apiVersion: apps/v1
kind: StatefulSet
# ...
# ...
template:
  spec:
      # ...
      # ...
      initContainers:
      {{- if .Values.initContainers }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.initContainers  "context" $ ) | nindent 8 }}
      {{- end }}

      {{- if .Values.extraInitContainers }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.extraInitContainers  "context" $ ) | nindent 8 }}
      {{- end }}
```

### values.yml

```yml
initContainers:
  - name: init-data
    image: busybox:latest
    command:
      ["sh", "-c", "chown -Rv 92:92 {{ .Values.persistence.storagePath }}"]
    volumeMounts:
      - name: data
        mountPath: "{{ .Values.persistence.storagePath }}"
```

### Expected Behavior

No segmentation violation but rendered docs.

### Reference Chart

https://github.com/tum-gis/sddi-ckan-k8s/pull/32

### Environment

- Operating system: Windows 10 and Ubuntu 22 tested
- Helm version (output of `helm version`): 3.14.0
- GO version (output of `go version`): 1.22 and 1.14 tested
- Method of calling `helm-docs` (manual, jenkins, github action ...): Tested docker and native install

### Link to `helm-docs` Logs

https://gist.github.com/BWibo/a9d3d7022836b22d86fe725e971883ae
