### ISSUE TITLE
[Feat]: Documenting values not explicitly present in values.yaml file

### ISSUE THREAD

**Issue by Cavaler** [norwoodj/helm-docs#225]
I am looking for a way to document some Helm chart values which are not actually written down in the values.yaml.

Here is a piece of the current values.yaml:
```
# -- One and only one should be configured
input: 
  # -- TCP connection
  tcp: {}
  # -- UDP connection
  udp: {}
  # -- Serial connection
  serial: {}
```
If for example `input.tcp` is not empty, then it is used as an input - with expected fields like host and port inside.
But I cannot document those fields now, since I have to include them in the map.

I'd like to be able to write something like this:

```
# -- One and only one should be configured
input: 
  # input.tcp.host -- (string) TCP host
  # input.tcp.port -- (int) TCP port
  tcp: {}
```

But currently these comments are just ignored.

**Comment by geekofalltrades** [comment]
We have this problem, as well, and I'll share what we do to work around it.

We have a chart that has a complex type for which the keys are user-defined, but the schema of the objects for the values is known and should be documented. Roughly:

```yaml
complex-value:
  user-defined-keys:
    known-key-1: foo
    known-key-2: bar
    known-key-3:
      user-defined-keys:
        known-key-4: foo
        known-key-5: bar
```

The value is a map of objects of a known type, but with user-defined keys. The known object type even contains another type that's the same: it, too, is a map of objects of a known type with user-defined keys.

For our docgen we do roughly:

```yaml
# -- Docs for complex-value
complex-value:
  # -- Docs for known type.
  example:
    # -- Docs for known-key-1
    known-key-1:
    # -- Docs for known-key-2
    known-key-2:
    # -- Docs for known-key-3
    known-key-3:
      # -- Docs for known type
      example1:
        # -- Docs for known-key-4
        known-key-4:
        # -- Docs for known-key-5
        known-key-5:
    # -- Docs for an alternative configuration of the known type
    example2:
```

And to work around the fact that `complex-value` now has a nonsensical default value, we have a helper function for interacting with it whose job is to test whether it has been set to something aside from the default.

```
{{/*
Check if complex-value has *actually* been defined.
Ignores the "example" value configured in the default Chart values file.
*/}}
{{- define "hasComplexValue" -}}
{{- $complexValueKeys := ($.Values.complex-value | keys | sortAlpha) }}
{{- $exampleKeys := (list "example" "example2" | toStrings) }}
{{- $out := deepEqual $exampleKeys $complexValueKeys | ternary "false" "true" }}
{{- printf "%s" $out }}
{{- end }}
```

In templates:

```
{{- if eq "true" (include "hasComplexValue" .) }}
# then actually do things with the value
{{- end }}
```

It seems like a great solution would be to be able to point helm-docs at an alternative values file to source its docgen comments from.

values.yaml:
```yaml
# We can have docs in here for simple values or values that have actual defaults.
# -- Docs for simple-type-with-default
simple-type-with-default: foo

# The actual default value of complex-type is null
complex-type:
```

values-helm-docs.yaml:
```yaml
# This file isn't used at all by the chart, just by helm-docs to generate additional docs.
# -- Docs for complex-type
complex-type:
  # -- Docs for complex-type's nested object
  example:
  # etc.
```
