### ISSUE TITLE
pre-commit scans the file only the first time 

### ISSUE THREAD

**Issue by slim-azaiz** [norwoodj/helm-docs#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the default config file
repos:
```
  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.13.1"
    hooks:
      - id: helm-docs
```

when i execute pre-commit it can not detect my README.md.tmpl
`Helm Docs............................................(no files to check)Skipped
`

### Expected Behavior

Helm Docs................................................................Passed

### Reference Chart

apiVersion: v2
name: occhart
description: A Helm chart for
type: application
version: 1.0.1

### Environment

- Operating system:
- Helm version (output of `helm version`):
- GO version (output of `go version`):
- Method of calling `helm-docs` (manual, jenkins, github action ...):
