### ISSUE TITLE
[Feat]: Section propagation

### ISSUE THREAD

**Issue by LBF38** [norwoodj/helm-docs#264]
### General Summary

Great tool, thanks for developing it !

A simple idea to reduce comments in `values.yaml` files would be to add `@section` propagation to fields, i.e. rather than commenting all values, only comment the top one and propagate the section to all children.

For example, it would be like this : 
```
# @section -- general config
key:
  # -- comments
  subkey: value
  # -- comments
  otherkey: value
  morekeys:
    # -- comments
    somekey:
      - value1
      - value2
``` 

### Is your feature request related to a problem? Please describe and/or link to a bug issue.

To reduce and limit the comments in values.yml and avoid unnecessary repetitions.

### Current Behavior

Currently, it is necessary to comment all values keys with the wanted section for organizing all values. It can quickly become repetitive.
