### ISSUE TITLE
Make it possible to document objects and arrays that are empty by default

### ISSUE THREAD

**Issue by ccremer** [norwoodj/helm-docs#39]
Let's consider this snippet:
```yaml
znapzend:
  # znapzend.args -- List of command arguments
  args:
    - znapzend
    - --logto=/dev/stdout
    - --autoCreation
  # znapzend.backupPlans -- List of backup plans to create/ensure on startup, see
  # [values.yaml](./values.yaml) for an example
  backupPlans: []
  # - dataset: pool/dataset
  ##  znapzend.backupPlans[].plan -- A backup plan object
  #   plan:
  #     selfResetAfter: 5m # Only effective when `metrics.enabled=true`, optional, default `1h`
  #     delaySeconds: 600 # Optional, default `0`
  #     source:
  #       retention: 1days=>2hours,2weeks=>1days,6months=>1weeks
  #       recursive: false # Optional, default `false`
  #     targets:
  #     - host: target.host
  #       dataset: backup/dataset
  #       retention: 1days=>2hours,2weeks=>1days,6months=>1weeks
```
Here, the `backupPlans[]` is empty, as there isn't a sensible default possible because it's dependent on the user's setup. If they don't like it, it's impossible to disable this with Helm's merging behaviour unless the users provide their own list. Hence the empty array.

However, it would still be cool to have the objects in the array documented in the README, as it's kind of inconvenient to have them look in the values.yaml file (see `znapzend.backupPlans[].plan`).

It's going to be difficult to implement, as the default YAML parsers ignore comments. But maybe we can add a `@type` to the value similar to `@default` done in https://github.com/norwoodj/helm-docs/pull/29, within double hashtag comments, e.g.
```yaml
  # znapzend.backupPlans -- List of backup plans to create/ensure on startup, see
  # [values.yaml](./values.yaml) for an example
  backupPlans: []
  ## znapzend.backupPlans[].dataset -- Source dataset path
  ## @type -- string
  ## @default -- ""
  # - dataset: pool/dataset
  ##  znapzend.backupPlans[].plan -- A backup plan object
  ## @type object
  #   plan: {} etc
```
* And maybe even parse the default type from the `@default`, e.g. `@default -- ""` becomes `string` if not specified by `@type`? 
* From my PoV helm-docs doesn't even need to parse the example. Generating the README by just providing the `## key -- description` and `## @default -- ""` and so on would be enough for me.

At the moment the generated README is just
```
| znapzend.backupPlans | list | `[]` | List of backup plans to create/ensure on startup, see [values.yaml](./values.yaml) for an example |
```
which ignores the documented example in `values.yaml` completely
