### ISSUE TITLE
[Feature request] Automatic field name

### ISSUE THREAD

**Issue by sparqueur** [norwoodj/helm-docs#58]
Hi,

Your README generator is really great ! :+1: 
However we still have to "adapt" our `value.yaml` file to provide the **field path** which is "intrusive" and "error prone".
```yaml
controller:
  # controller.persistentVolumeClaims -- List of persistent volume claims to create
  persistentVolumeClaims: []
```

There is this alternative project which automatically determine the **field path** : https://github.com/kubepack/chart-doc-gen
```yaml
controller:
  # List of persistent volume claims to create
  persistentVolumeClaims: []
```

Do you think you could be able to provide the same automatic behavior ?

Thanks in advance
