### ISSUE TITLE
Avoid the need to prefix value documentation with '---'

### ISSUE THREAD

**Issue by chgl** [norwoodj/helm-docs#67]
v1 made it unnecessary to specify the entire value path to generate the documentation, which is great! It would be even more convenient if the '---' were no longer required either. Ie:

```yaml
controller:
  # -- Configure the healthcheck for the ingress controller
  livenessProbe:
    httpGet:
      # -- This is the liveness check endpoint
      path: /healthz
```

Becomes:

```yaml
controller:
  # Configure the healthcheck for the ingress controller
  livenessProbe:
    httpGet:
      # This is the liveness check endpoint
      path: /healthz
```

This helps keep the values files more readable/easier to add documentation.

**Comment by norwoodj** [comment]
Hey @chgl I agonized over this when working on v1. My thinking in requiring the prefix was that it reflected the intent of the chart author that this comment should be parsed by helm-docs. I was concerned that if I went with this proposed solution users would be surprised occasionally by comments they intended not be parsed as descriptions making their way into a README, e.g.

```yaml
# This file is auto-formatted with yamlfmt, do not edit without re-running
deployment:
  image: hello:world
  replicas: 23

secret:
  enabled: false
  data: {}
```

In this case, the top comment would appear as a description for the `deployment` object, which would get its own row in the values table. Clearly in this case the intent is not for this to be treated as the description.

Of course, this issue could be mitigated by putting a single newline between the comment and the `deployment:` line, so maybe this is not actually an issue.

It's really up to you users. Pulling in all of the contributors:
@sc250024 @RemingtonReackhof @Artus-LHIND @matheusfm @ccremer @simoncaron @rbren @nvtkaszpir @acim @DirtyCajunRice 

What do y'all think about removing the prefix entirely from doc comments?
/polls "Require a -- prefix in description comments" "Use any comment on the line before a value as the description"

**Comment by norwoodj** [comment]
/polls "Require a -- prefix in description comments" "Use any comment on the line before a value as the description"

**Comment by ccremer** [comment]
Since #39 did not make it, I have use cases where I would document an example in values.yaml without having it parsed, especially in cases where empty arrays or objects are "documented" by comments to illustrate an example. Otherwise it would be interpreted as default value, which is wrong.

Having to duplicate each key with `# key.subkey --` syntax was annoying indeed. But I'd regard the new `# --` syntax as just a minor cosmetic issue now.

**Comment by ccremer** [comment]
@norwoodj 
What would you suggest to use as an alternative for adding comments that should _not_ get parsed if you remove the prefix requirement?

**Comment by chgl** [comment]
@ccremer my 2 cents: ignore any comment followed by a blank line. Ignore any comment starting with `@ignore` (or `@docignore` maybe)

**Comment by ccremer** [comment]
@chgl Please no confusing/hidden features with blank lines :smiley: I have already a hard time controlling whitespaces and newlines in Go templates and Jinja2

So basically this proposal is about reversing the comment behaviour: Normal comments get parsed, and special comments have another effect. In that case I'd rather have shorter notation for ignoring comments like `## some-comment`. Otherwise documenting a complex example over multiple lines each starting with `# @ignore ` is annoying too.

The `# Example` approach sounds interesting though. Maybe this could also be combined with the idea to have examples in external, dedicated YAML files to help with parsing examples (see https://github.com/norwoodj/helm-docs/issues/39#issuecomment-705415111). Helm docs would then load and parse an additional file and display the contents as example (inline in description, or maybe even it's own section in the readme)

**Comment by chgl** [comment]
@ccremer 
> Please no confusing/hidden features with blank lines

I feel like in this case it would be far more confusing if an expression like

```yaml
# Use these values to configure your deployment

some:
  # configure something here
  value: 123
```

would result in `Use these values to configure your deployment` documenting the `some` key.

Similar to `# Example`, maybe `# @ignore` could ignore the entire comment block?

**Comment by ccremer** [comment]
Well, extending on your example, how would we handle these cases:
```yaml
# yamllint disable-line rule:key-duplicates

# A comment that has blank lines before and after

some:
  # configure something here
  value: 123
  # an ignored comment, but semantically part of thing:

  # configure another thing
  thing:
  # what if an array is commented
  - arr1
  - arr2
  # what if we have multiple lines, indented, still "belonging" semantically to the content above
# or what if the next line is an empty comment
#
and-some-other-key: {}
```
I'm actually not sure if some of these cases are already handled regardless of a prefix. @norwoodj might give hints.

I dunno. With a prefix it makes it explicit and crystal clear whether a value is present in the README. Without a prefix, you'd have to know which style of comments have no effect in certain cases. I'd rather favor explicitness so that someone who doesn't know helm-docs can still contribute because the file follows visibly a certain style.

But if you guys don't want a prefix I'll accept that. Or try chart-doc-gen if need be :smiley:
