### ISSUE TITLE
Multi-line YAML using the <pre> tag for better readability

### ISSUE THREAD

**Issue by sc250024** [norwoodj/helm-docs#72]
Greetings,

I'm opening this issue for feedback to see what people think; maybe it's been opened before. Basically, I would like multi-line YAML blocks to be formatted using `<pre>` tags in Markdown rather than the current behavior, which is a single line block using backtick characters.

If I have a multi-line YAML block in `values.yaml` file like so:

```yaml
# -- Security context for the container level.
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
```

This will be rendered as follows in the current version of Helm Docs:

`{"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsNonRoot":true,"runAsUser":65534}`

As multi-line YAML blocks become large, this creates a slight readability problem. The https://github.com/terraform-docs/terraform-docs project handles this in a different way using `<pre>` blocks to look like the following directly in the Markdown:

<pre>securityContext:<br />  capabilities:<br />    drop:<br />    - ALL<br />  readOnlyRootFilesystem: true<br />  runAsNonRoot: true<br />  runAsUser: 65534</pre>

Here's the HTML of the above as it would be rendered in `terraform-docs` style:

```
<pre>securityContext:<br />  capabilities:<br />    drop:<br />    - ALL<br />  readOnlyRootFilesystem: true<br />  runAsNonRoot: true<br />  runAsUser: 65534</pre>
```

If you want to see a real example of this, you can check out the https://github.com/cloudposse/terraform-null-label#inputs repository, and under `Inputs`, look at the `context` block.

What do people think? Would this be preferred?
