### ISSUE TITLE
Default annotation is not used when value is null

### ISSUE THREAD

**Issue by paullaffitte** [norwoodj/helm-docs#84]
```yaml
# -- Field description
# @default -- Default value description
field:
```

Will output: ``| field | string | `nil` | Field description |``

Whereas
```yaml
# -- Field description
# @default -- Default value description
field: ""
```
Outputs: `| field | string | Default value description | Field description |`

**Comment by dennisvandehoef** [comment]
The bug seems to be already resolved: https://github.com/norwoodj/helm-docs/commit/a77f2e1ef9e6bae81c85526f07f59fb59b651bb8

Though in the latest docker image (containing the above-mentioned commit) this still happens.

```
# -- Main application web-pod's
# @default -- *See single entries  below for details*
appServer:
  disruptionBudget:
    # -- (int) Number of pods allowed to be unavailable (exclusive, not allowed in combination with minAvailable)
    # @default -- `1`
    maxUnavailable: ~
```

and

```
# -- Main application web-pod's
# @default -- *See single entries  below for details*
appServer:
  disruptionBudget:
    # -- (int) Number of pods allowed to be unavailable (exclusive, not allowed in combination with minAvailable)
    # @default -- `1`
    maxUnavailable:
```

both generate:
```
| Key | Type | Default | Description |
|-----|------|---------|-------------|
| appServer | object | *See single entries  below for details* | Main application web-pod's |
| appServer.disruptionBudget.maxUnavailable | int | `nil` | Number of pods allowed to be unavailable (exclusive, not allowed in combination with minAvailable) |
```
