### ISSUE TITLE
[Enhancement] Allow us to set target file and directory

### ISSUE THREAD

**Issue by jeroenjacobs79** [norwoodj/helm-docs#89]
It seems impossible at the moment to customize the directory of the generated readme. 

I have my helm chart in a sub-folder, and as a result, the README is always generated in that subfolder.

e.g:

my helm chart is located in the `./helm` subfolder. My config looks like this:

```
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.4.0
  hooks:
    - id: helm-docs
      args:
        - --chart-search-root=helm
        - --template-files=../README.md.gotmpl
```

I want to keep my `helm` directory clean, so I already managed to keep the template out of the helm folder by using `../README.md.gotmpl`.

Now, how do I prevent the readme of being generated in the `./helm` folder, and just in my top-level folder? Specifying the output destination of a generated file, doesn't feel like an uncommon thing...

**Comment by norwoodj** [comment]
The thing about it is that the tool supports potentially many helm charts within a repository. As such, it doesn't make sense to generate the README anywhere but in the root of each chart.

In this case, if there's just one chart under helm, why not make that the repository root? If there are other things in this repository, do you really want the repository README to be the auto-generated chart documentation?

I'm just trying to understand your use case. There's likely something we can figure out that will make this easier for you.

**Comment by Sanea2pk** [comment]
Hi @jeroenjacobs79  
You can use `--output-file` option to specify where do you what to generate the `README.md` file. The path should be relative to your `helm` directory.

**Example**:
```yaml
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.11.0
  hooks:
  - id: helm-docs
    args:
    # Make the tool search for charts only under the `helm` directory
    - --chart-search-root=./helm
    - --output-file=../README.md
```
