### ISSUE TITLE
pre-commit hook template in subdir not working

### ISSUE THREAD

**Issue by HaveFun83** [norwoodj/helm-docs#91]
Hi 

thanks a lot for this great project.

i have a strange issue with a custom gotemplate within a subdir.
When i run helm-doc cli manually i got the exspected result:

```bash
❯ helm-docs --chart-search-root=. --template-files=README.md.gotmpl --template-files=./templates/_templates.gotpl -l debug
DEBU[2021-03-23T17:44:25+01:00] No ignore file found at helm-charts/.helmdocsignore, using empty ignore rules 
INFO[2021-03-23T17:44:25+01:00] Found Chart directories [.]                  
DEBU[2021-03-23T17:44:25+01:00] Rendering from optional template files [README.md.gotmpl, templates/_templates.gotpl] 
INFO[2021-03-23T17:44:25+01:00] Generating README Documentation for chart helm-charts/example
DEBU[2021-03-23T17:44:25+01:00] Using template files [README.md.gotmpl templates/_templates.gotpl] for chart helm-charts/example
```
but when i run exactly the same via pre-commit hook the template within the subdir was not found
```bash
❯ pre-commit run
Helm Docs................................................................Failed
- hook id: helm-docs
- files were modified by this hook

DEBU[2021-03-23T17:44:30+01:00] No ignore file found at helm-charts/.helmdocsignore, using empty ignore rules 
DEBU[2021-03-23T17:44:30+01:00] Ignoring directory helm-charts/.git 
INFO[2021-03-23T17:44:30+01:00] Found Chart directories [example] 
DEBU[2021-03-23T17:44:30+01:00] Rendering from optional template files [README.md.gotmpl, ./templates/_templates.gotpl] 
INFO[2021-03-23T17:44:30+01:00] Generating README Documentation for chart helm-charts/example 
DEBU[2021-03-23T17:44:30+01:00] Did not find template file ./templates/_templates.gotpl for chart helm-charts/example, using default template
```

when i move the `_templates.gotpl` under the chart root everything is working as expected.

**Comment by norwoodj** [comment]
Aha, I was worried about this, the [example .pre-commit-config.yaml file in this repo](https://github.com/norwoodj/helm-docs/blob/master/.pre-commit-config.yaml) sets some special flags in order to work in _this_ repo. You should remove all of:
```
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=example-charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl
```

from your file

**Comment by norwoodj** [comment]
Can you send me the contents of your `.pre-commit-config.yaml` file? I suspect this is not a bug, but something misconfigured in your file (I hope).

**Comment by HaveFun83** [comment]
> Can you send me the contents of your `.pre-commit-config.yaml` file? I suspect this is not a bug, but something misconfigured in your file (I hope).

Sure:
```
repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.5.0
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=.

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=README.md.gotmpl

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=_templates.gotpl

          #- --log-level=debug
```
