### ISSUE TITLE
The description is missing if some unrelated comment exists before the value description.

### ISSUE THREAD

**Issue by Wing924** [norwoodj/helm-docs#92]
# input values.yaml:

```yaml
# comment 1

# -- key1
key1: {}

# comment 2

# -- key2
key2: {}
```

# expect output:

## Values

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| key1 | object | `{}` | key1 |
| key2 | object | `{}` | key2 |

# actual output:

## Values

| Key | Type | Default | Description |
|-----|------|---------|-------------|
| key1 | object | `{}` | key1 |
| key2 | object | `{}` |  |
