### ISSUE TITLE
The description includes description of previous commented values

### ISSUE THREAD

**Issue by kaworu** [norwoodj/helm-docs#96]
Might be related to https://github.com/norwoodj/helm-docs/issues/92
## values.yaml
```yaml
# -- before desc
before: ~

# -- commented desc
#commented: ~

# -- after desc
after: ~
```
## expected output
| Key | Type | Default | Description |
|-----|------|---------|-------------|
| after | string | `nil` | after desc |
| before | string | `nil` | before desc |
## actual output
| Key | Type | Default | Description |
|-----|------|---------|-------------|
| after | string | `nil` | commented desc -- after desc |
| before | string | `nil` | before desc |
